name: AppImage Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install appimage-builder
      run: |
        sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
        sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
        sudo chmod +x /usr/local/bin/appimagetool
        
        # use latest appimage-builder which includes the no_hooks entry 
        sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git
    - name: Create AppImage
      run: |
        export BFORARTITS_VERSION=2.9.3
        appimage-builder --recipe appimage-builder.yml --skip-test
    - name: Save build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AppImage
        path: './*.AppImage*'
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Continuous build
        automatic_release_tag: 'continuous'
        prerelease: true
        draft: false
        files: './*.AppImage*'
        repo_token: ${{ secrets.GITHUB_TOKEN }}